"""empty message

Revision ID: d471a6cc38ad
Revises: b4389cb3fe3d
Create Date: 2023-03-30 17:15:31.555029

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd471a6cc38ad'
down_revision = 'b4389cb3fe3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
