"""add index

Revision ID: fb3129b3ef99
Revises: 9707ffb950c4
Create Date: 2023-04-17 17:13:09.293392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb3129b3ef99'
down_revision = '9707ffb950c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('idx_profiles_user_id', ['user_id'], unique=False)
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profiles_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_profiles_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_index('idx_profiles_user_id')

    # ### end Alembic commands ###
